version: 0.2

phases:
  install:
    commands:
      - curl -sS https://getcomposer.org/installer | sudo php && mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - composer install
  post_build:
    commands:
      - mv .env.stg .env
artifacts:
  type: zip
  files:
    - '**/*'